spring.application.name=currency-service
server.port=8100

#config database connection
spring.datasource.url=jdbc:postgresql://localhost:5432/db_currency
spring.datasource.username=postgres
spring.datasource.password=postgres

#in production
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#spring migrations configuration
spring.flyway.locations=classpath:/db_migration